package server

import (
	"context"
	"log"

	"github.com/gogo/status"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
)

// Validator contains methods generated by the validator plugin.
type Validator interface {
	Validate() error
}

// ServerValidationUnaryInterceptor returns a new unary server interceptor that validates incoming requests.
func ServerValidationUnaryInterceptor(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp interface{}, err error) {
	if r, ok := req.(Validator); ok {
		if err := r.Validate(); err != nil {
			log.Printf("ERROR: Validate: %+v", err)
			return nil, status.Error(codes.InvalidArgument, err.Error())
		}
	}

	return handler(ctx, req)
}
