FROM fedora:38

RUN dnf install -y tinygo binaryen

ARG RUST_TOOLCHAIN="1.71.0"
ENV CARGO_HOME=/usr/local/rust
ENV RUSTUP_HOME=/usr/local/rust
ENV PATH="$PATH:$CARGO_HOME/bin"

RUN curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain "$RUST_TOOLCHAIN" && \
    rustup target add wasm32-wasi
